version: '3.8'

services:
  wemo-backend:
    build: .
    container_name: wemo_ai_core
    ports:
      - "80:5000" 
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped